version: '3'
services:

  yugabyte:
    image: yugabytedb/yugabyte:latest
    command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
    ports:
      - '7000:7000'
      - '9000:9000'
      - '5433:5433'
      - '9042:9042'
    volumes:
      - ~/yb_data:/home/yugabyte/yb_data
