apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - name: service
      port: 9000
      targetPort: 9000
      nodePort: 31000
      protocol: TCP
    - name: ui
      port: 9001
      targetPort: 9001
      nodePort: 32000
      protocol: TCP
  selector:
    app: minio